services:
  # agent services
  agent:
    build:
      context: ./
      dockerfile: dockerfile_agent
    container_name: agent
    depends_on:
      - ranking_chitchat_2stage
      - neuro_chitchat_odqa_selector
      - odqa
      - mongo
    env_file: agent.env
    ports:
      - 4242:4242
    tty: true
    volumes:
      - .:/dp-agent
  mongo:
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/db:/root/data/db

  # selector services
  rule_based_selector:
    build:
      args:
        SERVICE_NAME: rule_based_selector
        SERVICE_PORT: 2086
      context: ./services/selectors/rule_based_selector/
      dockerfile: Dockerfile
    container_name: rule_based_selector
    environment:
      - CUDA_VISIBLE_DEVICES=""
    ports:
      - 2086:2086
    tty: true
    volumes:
      - ./services/selectors/rule_based_selector:/src

  neuro_chitchat_odqa_selector:
    build:
      args:
        PYTHON_BASE_IMAGE: python:3.7-slim-stretch
        COMMIT: dp_agent/skill_selector/chitchat_vs_odqa
        SERVICE_CONFIG: ru_skills_selector_bert
        SERVICE_PORT: 2082
      context: ./
      dockerfile: services/deeppavlov/custom_cpu_dockerfile
    container_name: neuro_chitchat_odqa_selector
    environment:
      - CUDA_VISIBLE_DEVICES=""
    ports:
      - 2082:2082
    tty: true
    volumes:
      - ${EXTERNAL_FOLDER}/dp_logs:/logs
      - ${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov
      - ${EXTERNAL_FOLDER}/tfhub:/tmp/tfhub
      - .:/base/dp-agent

  # skill services
  greeting_skill:
    build:
      args:
        SERVICE_NAME: greeting_skill
        SERVICE_PORT: 2087
      context: ./services/skills/greeting_skill/
      dockerfile: Dockerfile
    container_name: greeting_skill
    environment:
      - CUDA_VISIBLE_DEVICES=""
    ports:
      - 2087:2087
    tty: true
    volumes:
      - ./services/skills/greeting_skill:/src
  odqa:
    build:
      args:
        BASE_IMAGE: deeppavlov/base-cpu:0.6.1
        SERVICE_CONFIG: odqa/ru_odqa_infer_wiki_rubert_noans
        SERVICE_PORT: 2080
      context: ./
      dockerfile: services/deeppavlov/dockerfile_skill
    container_name: odqa
    environment:
      - CUDA_VISIBLE_DEVICES="0"
    ports:
      - 2080:2080
    tty: true
    volumes:
      - ${EXTERNAL_FOLDER}/dp_logs:/logs
      - ${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov
      - ${EXTERNAL_FOLDER}/tfhub:/tmp/tfhub
  ranking_chitchat_2stage:
    build:
      args:
        PYTHON_BASE_IMAGE: python:3.7-slim-stretch
        COMMIT: feat/agnostic_retrieval_chitchat
        SERVICE_CONFIG: services/skills/ranking_chitchat_2stage/ranking_chitchat_2staged_tfidf_smn_v22_a.json
        # SERVICE_CONFIG: services/skills/ranking_chitchat_2stage/ranking_chitchat_2staged_tfidf_smn_v23_g.json
        # SERVICE_CONFIG: services/skills/ranking_chitchat_2stage/ranking_chitchat_2staged_tfidf_smn_v24_a.json
        # SERVICE_CONFIG: services/skills/ranking_chitchat_2stage/ranking_chitchat_2staged_tfidf_smn_v24_a_debug.json
        SERVICE_PORT: 2085
      context: ./
      dockerfile: services/deeppavlov/custom_cpu_dockerfile
    container_name: ranking_chitchat_2stage
    environment:
      - CUDA_VISIBLE_DEVICES=""
    ports:
      - 2085:2085
    tty: true
    volumes:
      - ${EXTERNAL_FOLDER}/dp_logs:/logs
      - ${EXTERNAL_FOLDER}/.deeppavlov:/root/.deeppavlov
      - ${EXTERNAL_FOLDER}/tfhub:/tmp/tfhub
      - .:/base/dp-agent
version: "3.7"
